apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 8088  # The port exposed by the service (80)
      protocol: TCP
      targetPort: 80 # The target port of the pods
  selector:
    run: nginx-clusterip