apiVersion: v1
kind: Pod
metadata:
  name: failed-multi-container-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:i-do-not-exist
    - name: busybox-container
      image: busybox:latest
      command: ["sleep", "3600"]