apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  annotations:
    tier: webserver
  labels:
    environment: prod
    tier: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx:latest