apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod-with-host-path
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /var/config
          name: my-host-path-volume
    - name: busybox-container
      image: busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 30; done;"]
  volumes:
    - name: my-host-path-volume
      hostPath:
        path: /tmp