apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-configmap
spec:
  containers:
    - name: nginx-container-with-configmap
      image: nginx:latest
      env:
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              name: my-third-configmap
              key: color