apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-nodeport
spec:
  type: NodePort
  selector:
    app: nginx
    environment: test
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 80