apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-secret-env-variable
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      env:
        - name: PASSWORD_ENV_VAR
          valueFrom:
            secretKeyRef:
              name: my-first-secret
              key: db_password