apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset-example
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
    matchExpressions:
      - key: environment
        operator: In
        values:
          - dev
          - test
  template:
    metadata:
      labels:
        app: nginx
        environment: dev
    spec:
      containers:
        - name: nginx
          image: nginx:1.17
          ports:
            - containerPort: 80