apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox-custom-command-args
spec:
  initContainers:
    - name: my-init-container
      image: busybox:latest
      command: ["sleep", "15"]
  containers:
    - name: nginx-container
      image: nginx:latest
    - name: busybox-container
      image: busybox:latest
      command: ["sleep"]
      args: ["60"]