apiVersion: v1
kind: Service
metadata:
  name: nginx-client
spec:
  selector: # target specific pods with this load balancer
    app: nginx-stateful
    environment: test
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80