apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-stateful
      environment: test
  serviceName: nginx-headless
  template:
    metadata:
      labels:
        app: nginx-stateful
        environment: test
    spec:
      containers:
        - name: nginx
          image: nginx:1.17
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-data
          command:
            - /bin/sh
            - -c
            - |
              echo "You have been served by Pod with IP address: $(hostname -i)" > /usr/share/nginx/html/index.html
              nginx -g "daemon off;"
  volumeClaimTemplates:
    - metadata:
        name: nginx-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
