apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-secret-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /etc/password-mounted-path
          name: my-secret-volume
  volumes:
    - name: my-secret-volume
      secret:
        secretName: my-stormy-secret