apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      environment: test
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx
        environment: test
    spec:
      containers:
        - name: nginx
          image: nginx:1.18
          ports:
            - containerPort: 80
          command:
            - /bin/sh
            - -c
            - |
              touch /usr/share/nginx/html/ready
              echo "You have been served by Pod with IP address: $(hostname -i)" > /usr/share/nginx/html/index.html
              nginx -g "daemon off;"
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 5  # start pinging 5 seconds after container starts
            periodSeconds: 2 # ping in 2 second intervals
            timeoutSeconds: 10 # timeout threshold for the http get request
            successThreshold: 1 # number of success responses before it's considered a success
            failureThreshold: 2 # number of failed requests before it's considered a failure