apiVersion: v1
kind: Service
metadata:
  name: nginx-daemon-headless
spec:
  selector:
    app: nginx-daemon
    environment: test
  clusterIP: None  # headless svc, exposes all matching Pods with A name
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80