apiVersion: v1
kind: Service
metadata:
  name: nodeport-whoami
spec:
  type: NodePort
  selector:
    app: whoami
#  sessionAffinity: None
#  sessionAffinityConfig:
#    clientIP:
#      timeoutSeconds: 1
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 80