apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-request-and-limit-2
  namespace: custom-ns-with-resource-quota
spec:
  containers:
    - name: nginx-2
      image: nginx:latest
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "1000m"