apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-request-and-limit-5
  namespace: custom-ns
spec:
  containers:
    - name: nginx-5
      image: nginx:latest
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "1000m"