apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-request
  namespace: custom-ns-with-resource-quota
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"