apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-hostpath-pv
  labels:
    type: hostpath
    env: prod
spec:
  capacity:
    storage: 1Gi
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"