apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resourcequota-object-count
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: "1Gi"
    limits.cpu: "2000m"
    limits.memory: "2Gi"
    configmaps: "1"
    services: "5"